#define __bss_end Load$$bss_percpu$$Limit
#if 0
#define __bss_start
#define __init_end_efi
#define _end
#define _start
#define __2snprintf
#define __initcall_end
#define __initcall_start
#define __param_end
#define __param_start
#define __presmp_initcall_end
#define __setup_end
#define __setup_start
#define _printf_c
#define _printf_percent
#define _printf_str
#define __ctors_end
#define __ctors_start
#define __end_schedulers_array
#define __start_schedulers_array
#define _einittext
#define _etext
#define _sinittext
#define __start_bug_frames
#define __stop_bug_frames_0
#define __stop_bug_frames_1
#define __stop_bug_frames_2
#define _stext
#define _printf_d
#define _printf_flags
#define _printf_int_dec
#define _printf_llu
#define _printf_llx
#define _printf_longlong_dec
#define _printf_longlong_hex
#define _printf_pre_padding
#define _printf_sizespec
#define _printf_u
#define _printf_widthprec
#define __alt_instructions
#define __alt_instructions_end
#define _aedevice
#define _asdevice
#define _edevice
#define _sdevice
#define __init_begin
#define __init_end
#define _erodata
#define _srodata
#define __per_cpu_data_end
#define __per_cpu_start
#define _eplatform
#define _splatform
#define _printf_return_value
#define _printf_s
#endif
